update for week4

diff --git a/backend-flask/bin/db-setup b/backend-flask/bin/db-setup
--- a/backend-flask/bin/db-setup
+++ b/backend-flask/bin/db-setup
@@ -1,5 +1,6 @@
 #! /usr/bin/bash
--e # stop if it fails at any point
+
+set -e # stop if it fails at any point
 
 #echo "==== db-setup"
 CYAN='\033[1;36m'
@@ -9,6 +10,7 @@ printf "${CYAN}==== ${LABEL}${NO_COLOR}\n"
 
 bin_path="$(realpath .)/bin"
 
+echo $bin_path
 source "$bin_path/db-drop"
 source "$bin_path/db-create"
 source "$bin_path/db-schema-load"
